const dashboardWidgets = [
	{
		id: 1,
		cardColor: 'success',
		label: 'Total Categories',
		badge: 'ri-arrow-right-up-line',
		badgeClass: 'success',
		percentage: '+29.08',
		counter: 20,
		link: 'View Total Categories',
		bgcolor: 'success',
		icon: 'ri-bubble-chart-line',
		decimals: 2,
		prefix: '',
		suffix: 'M',
		linkTo :'/category'
	},
	{
		id: 2,
		cardColor: 'info',
		label: 'Total Tickets',
		badgeClass: 'muted',
		percentage: '+0.00',
		counter: 30,
		link: 'View Total Tickets',
		bgcolor: 'primary',
		icon: 'ri-coupon-line',
		decimals: 2,
		prefix: '$',
		suffix: '',
		linkTo :'/total-tickets'
	},
	{
		id: 3,
		cardColor: 'info',
		label: 'Recent Tickets',
		badgeClass: 'muted',
		percentage: '+0.00',
		counter: 5,
		link: 'View Recent Tickets',
		bgcolor: 'info',
		icon: 'ri-history-line',
		decimals: 2,
		prefix: '$',
		suffix: 'k',
		linkTo :'/recent-tickets'
	},
	{
		id: 4,
		cardColor: 'info',
		label: 'Active Tickets',
		badgeClass: 'muted',
		percentage: '+0.00',
		counter: 4,
		link: 'View Active Tickets',
		bgcolor: 'success',
		icon: 'ri-ticket-2-fill',
		decimals: 2,
		prefix: '$',
		suffix: 'm',
		linkTo :'/active-tickets'
	},
	{
		id: 5,
		cardColor: 'info',
		label: 'Closed Tickets',
		badgeClass: 'muted',
		percentage: '+0.00',
		counter: 15,
		link: 'View Closed Tickets',
		bgcolor: 'danger',
		icon: 'ri-honour-fill',
		decimals: 2,
		prefix: '$',
		suffix: 'k',
		linkTo :'/closed-tickets'
	},
	{
		id: 6,
		cardColor: 'info',
		label: 'ON-Hold Tickets',
		badgeClass: 'muted',
		percentage: '+0.00',
		counter: 5,
		link: 'View ON-Hold Tickets',
		bgcolor: 'secondary',
		icon: 'ri-hand-coin-fill',
		decimals: 2,
		prefix: '$',
		suffix: 'k',
		linkTo :'/on-hold-tickets'
	},
	{
		id: 7,
		cardColor: 'info',
		label: 'Overdue Tickets',
		badgeClass: 'muted',
		percentage: '+0.00',
		counter: 2,
		link: 'View Overdue Tickets',
		bgcolor: 'primary',
		icon: 'ri-timer-flash-line',
		decimals: 2,
		prefix: '$',
		suffix: 'k',
		linkTo :'/over-due-tickets'
	},
	{
		id: 8,
		cardColor: 'info',
		label: 'Assigned Tickets',
		badgeClass: 'muted',
		percentage: '+0.00',
		counter: 23,
		link: 'View Assigned Tickets',
		bgcolor: 'primary',
		icon: 'bx bx-user-plus',
		decimals: 2,
		prefix: '$',
		suffix: 'k',
		linkTo :'/assigned-tickets'
	},
	{
		id: 9,
		cardColor: 'info',
		label: 'Unassigned Tickets',
		badgeClass: 'muted',
		percentage: '+0.00',
		counter: 10,
		link: 'View Unassigned Tickets',
		bgcolor: 'primary',
		icon: 'bx bx-user-minus',
		decimals: 2,
		prefix: '$',
		suffix: 'k',
		linkTo :'/unassigned-tickets'
	},
	{
		id: 10,
		cardColor: 'info',
		label: 'Trashed Tickets',
		badgeClass: 'muted',
		percentage: '+0.00',
		counter: 3,
		link: 'View Trashed Tickets',
		bgcolor: 'danger',
		icon: 'bx bx-trash',
		decimals: 2,
		prefix: '$',
		suffix: 'k',
		linkTo :'/trashed-tickets'
	},
];

export { dashboardWidgets };
